name: Run Tests

on:
    push:
        branches:
          - main
    pull_request:
        branches:
          - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up LuaJIT
            uses: leafo/gh-actions-lua@v11
            with:
                luaVersion: "luajit"

          - name: Install LuaRocks
            uses: leafo/gh-actions-luarocks@v5
            with:
                luarocksVersion: "3.12.0"

          - name: Install dependencies
            run: |
                luarocks install busted
                luarocks install luacov
                luarocks install luacov-reporter-lcov

          - name: Run tests with coverage
            run: |
                busted --lua=luajit -m=./?/init.lua -c

          - name: Generate lcov report
            run: |
                luacov -r lcov

          - name: Upload coverage to Codecov
            uses: codecov/codecov-action@v5
            with:
                token: ${{ secrets.CODECOV_TOKEN }}
                files: luacov.report.out
